"""Acceptance oracle for the aa_srcsec_probe source-security fixture.

Run:  python -m aa_srcsec_probe.check_srcsec   (argv-only, stdlib-only, cwd=/workspace)
Exit 0 == green, exit 1 == red.

WHAT IT PINS, AND WHY IT IS GREEN BEFORE AND AFTER. The verdict on a source
security patch is the scanner delta (high+critical must strictly drop), not this
file. This oracle exists for the opposite reason: to stop a "fix" that makes the
finding disappear by deleting the code that was findable. Removing
get_user_by_id, or making it return None unconditionally, would drop the count
to zero and look like a perfect patch.

So this asserts only the OBSERVABLE lookup contract -- the right row comes back
for a known id, and None for an unknown one. It deliberately says nothing about
how the statement is assembled or passed to the driver, which is exactly the
part a patch is free to change. The fake cursor below therefore accepts both the
one-argument and the parameterized two-argument execute() call.

Do not edit this file -- it is the oracle, not the subject.
"""
import re
import sys

from aa_srcsec_probe.queries import get_user_by_id

ROWS = {1: (1, "alice"), 2: (2, "bob")}


class FakeCursor:
    """Minimal DB-API stand-in that resolves an id from either call shape."""

    def __init__(self):
        self._row = None

    def execute(self, sql, params=None):
        if params:
            wanted = params[0] if isinstance(params, (tuple, list)) else params
        else:
            m = re.search(r"id\s*=\s*'?(-?\d+)'?", sql)
            wanted = m.group(1) if m else None
        try:
            wanted = int(wanted)
        except (TypeError, ValueError):
            wanted = None
        self._row = ROWS.get(wanted)

    def fetchone(self):
        return self._row


def main() -> int:
    failures: list[str] = []

    for user_id, expected in ((1, ROWS[1]), (2, ROWS[2])):
        got = get_user_by_id(FakeCursor(), user_id)
        if got != expected:
            failures.append(
                "get_user_by_id(cursor, %r) == %r, expected %r" % (user_id, got, expected)
            )

    missing = get_user_by_id(FakeCursor(), 99)
    if missing is not None:
        failures.append("get_user_by_id(cursor, 99) == %r, expected None" % (missing,))

    if failures:
        for f in failures:
            print("FAIL: %s" % f)
        return 1

    print("PASS: aa_srcsec_probe user lookup behaviour is unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
