"""Acceptance oracle for the aa_iac_probe IaC fixture.

Run:  python -m aa_iac_probe.check_iac      (argv-only, stdlib-only, cwd=/workspace)
Exit 0 == green, exit 1 == red.

WHAT IT PINS, AND WHY IT IS GREEN BEFORE AND AFTER. The verdict on an IaC
security patch is the scanner delta (high+critical must strictly drop), not this
file. This oracle exists for the opposite reason: to stop a "fix" that makes the
finding disappear by removing the thing that was findable. Deleting the security
group, or deleting its SSH ingress rule, would drop the count to zero and look
like a perfect patch. So this file asserts only that the declaration still
EXISTS and still exposes SSH -- never where SSH may be reached FROM, which is
exactly the part a patch is free to change.

Do not edit this file -- it is the oracle, not the subject.
"""
import re
import sys
from pathlib import Path

MANIFEST = Path(__file__).resolve().parent / "insecure_sg.tf"
RESOURCE = 'resource "aws_security_group" "aa_iac_probe_ssh"'


def _strip_comments(text: str) -> str:
    """Drop whole-line HCL comments so they cannot unbalance the brace scan."""
    kept = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("//"):
            continue
        kept.append(line)
    return "\n".join(kept)


def _block_at(text: str, start: int) -> str:
    """Return the {...} block whose opening brace follows index `start`."""
    open_at = text.find("{", start)
    if open_at == -1:
        return ""
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_at : i + 1]
    return ""


def _sub_blocks(body: str, kind: str) -> list[str]:
    blocks = []
    for m in re.finditer(r"\b%s\b\s*\{" % re.escape(kind), body):
        block = _block_at(body, m.start())
        if block:
            blocks.append(block)
    return blocks


def _port(block: str, field: str) -> str | None:
    m = re.search(r"\b%s\b\s*=\s*(\d+)" % re.escape(field), block)
    return m.group(1) if m else None


def main() -> int:
    failures: list[str] = []

    if not MANIFEST.is_file():
        print("FAIL: %s is missing" % MANIFEST.name)
        return 1

    text = _strip_comments(MANIFEST.read_text(encoding="utf-8"))

    idx = text.find(RESOURCE)
    if idx == -1:
        failures.append("the %s declaration is gone" % RESOURCE)
        body = ""
    else:
        body = _block_at(text, idx + len(RESOURCE))
        if not body:
            failures.append("the security group block is unbalanced or empty")

    if body:
        ingress = _sub_blocks(body, "ingress")
        if not ingress:
            failures.append("the security group declares no ingress rule")
        else:
            ssh = [
                b
                for b in ingress
                if _port(b, "from_port") == "22" and _port(b, "to_port") == "22"
            ]
            if not ssh:
                failures.append(
                    "no ingress rule exposes TCP/22 any more -- narrowing the "
                    "source is a patch, deleting SSH access is not"
                )

        if not _sub_blocks(body, "egress"):
            failures.append("the security group declares no egress rule")

    if failures:
        for f in failures:
            print("FAIL: %s" % f)
        return 1

    print("PASS: aa_iac_probe security group still declares SSH ingress and egress")
    return 0


if __name__ == "__main__":
    sys.exit(main())
