"""Acceptance check for the aacyc_* CROSS-COMPONENT refactoring fixture.

Run:  python -m src.aacyc_check          (argv-only, standard library only, cwd=/workspace)

WHAT IT PINS. The seeded defect is the module-level cycle
    src/aacyc_alpha -> src/aacyc_beta -> src/aacyc_gamma -> src/aacyc_alpha
which is CROSS-DIRECTORY, so the architecture analyzer resolves three components and
`architectureCycleCheck` can actually see it. (The older same-directory `aa_refactor_probe`
fixture cannot be seen at all: component_extractor collapses one directory into ONE component
and drops same-component edges before Tarjan runs, so it returns `cycles: []` -- a vacuous PASS.)

A CORRECT refactor removes at least one module-level edge of that cycle while these three
observable behaviours stay EXACTLY the same. Behaviour is the invariant; structure is the work.
Do not edit this file -- it is the oracle, not the subject.
"""
import sys


def main() -> int:
    from src.aacyc_alpha.core import chain as alpha_chain
    from src.aacyc_beta.core import chain as beta_chain
    from src.aacyc_gamma.core import chain as gamma_chain

    expected = {"alpha": "b", "beta": "c", "gamma": "a"}
    actual = {"alpha": alpha_chain(), "beta": beta_chain(), "gamma": gamma_chain()}

    if actual != expected:
        print("FAIL: behaviour changed. expected %r, got %r" % (expected, actual))
        return 1
    print("PASS: aacyc alpha/beta/gamma chain behaviour is unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
