"""Acceptance check for the aacyc2_* CROSS-COMPONENT refactoring fixture.

Run:  python -m src.aacyc2_check          (argv-only, standard library only, cwd=/workspace)

WHAT IT PINS. The seeded defect is the module-level cycle
    src/aacyc2_alpha -> src/aacyc2_beta -> src/aacyc2_gamma -> src/aacyc2_alpha
which is CROSS-DIRECTORY, so the architecture analyzer resolves three components and
`architectureCycleCheck` can actually see it.

A CORRECT refactor removes at least one module-level edge of that cycle while these three
observable behaviours stay EXACTLY the same. Behaviour is the invariant; structure is the work.
Do not edit this file -- it is the oracle, not the subject.

WHY A SECOND FIXTURE EXISTS. The original aacyc_* fixture was SPENT on 2026-09-01: the
conveyor's own PRs #126 and #128 were merged into aa/arch-refactor-cycle-fixture, deferring
the alpha and gamma imports into functions. With no closed ring left, every drive off that
branch is vacuous BY CONSTRUCTION -- an empty baseline is then the truth, and a green cannot
go red. That branch is deliberately left as-is and now serves as the NEGATIVE CONTROL: a
drive against it must ABSTAIN, not pass.
"""
import sys


def main() -> int:
    from src.aacyc2_alpha.core import chain as alpha_chain
    from src.aacyc2_beta.core import chain as beta_chain
    from src.aacyc2_gamma.core import chain as gamma_chain

    expected = {"alpha": "b", "beta": "c", "gamma": "a"}
    actual = {"alpha": alpha_chain(), "beta": beta_chain(), "gamma": gamma_chain()}

    if actual != expected:
        print("FAIL: behaviour changed. expected %r, got %r" % (expected, actual))
        return 1
    print("PASS: aacyc2 alpha/beta/gamma chain behaviour is unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
